# Conclusion
In conclusion, our analysis of global greenhouse gas emissions shows a multidimensional picture of changing emission trends by various sectors in different countries
over the years. Firstly, even though CO2 continues to dominate the global emissions, F-gas emissions have increased over the years raising concerns about more sources
of emissions apart from the existing CO2 sources. Whereas gases like CH4 and N2O have also seen rise in the emission levels, but their increase doesn't seem to be
as alarming as that of CO2 and F-gas. Further, delving into to sector wise analysis helps us realize that Energy and Electricity/Heat sectors have been the front runners in the emissions of CO2. While the agriculture sector is the major source of CH4 and N2O which can be attributed to activities related to livestock. These observations call for the need to adapt and shift to sustainable practices such as increasing the usage of renewable energy systems, adopting practices in agriculture that reduce emissions of methane and producing electricity in an efficient manner. Recognizing these trends would help the policymakers, leaders and researchers develop techniques to reduce the overall emission of these gases, progress towards the goal of Net Zero Carbon emission, incentivize climate friendly and sustainable practices. Moreover, shifting the lens to country-level
emission trends we see that some nations have seen a steep rise in the amount of emissions over the years, while some have displayed a stable pattern and others showing 
a gradual decline in the emissions. Specifically, China, United States and India have been among the top emitters of these gases in 2021. Over the years, China has seen
a steep rise in the emissions of these gases, mainly CO2, while India showing a gradual rise and United States have displayed stable patterns. Countries  in the European
Union have observed a decline in the emission of all the gases in some major sectors over the years except F-gas, which has increased gradually. 
To conclude, as the emission trends emerge, data collection and analysis of these trends will be crucial in the future to track the emissions and monitor the progress
towards net zero target and developing sustainable practices. Moreover, these emissions call for global efforts to make collective efforts and adopt best practices to
progress towards more sustainable future. 